### ISSUE TITLE
Option to tweak FEATURES

### ISSUE THREAD

**Issue by alarig** [nicolasbock/ebuildtester#119]
Hi,

When I run a build, the FEATURES are tweaked
```
2020-04-25 14:34:39,014 - 08523b echo FEATURES=\"-sandbox -usersandbox\" >> /etc/portage/make.conf
```

However, the wiki enables the sandbox: https://wiki.gentoo.org/wiki/Package_testing

How is it possible to force it?

**Comment by stkw0** [comment]
I don't think it's possible now but it would be nice to have

**Comment by nicolasbock** [comment]
It wasn't very hard to add actually. @stkw0 and @alarig , could you take a look at #182 ? Thanks!
