### ISSUE TITLE
Forking for usage with podman

### ISSUE THREAD

**Issue by epsilon-0** [nicolasbock/ebuildtester#122]
Am going to try to get this to work using podman instead of docker, mostly because podman is nicer to integrate with the system and can work with an unprivileged account.

Just wanted to let you know about my endeavor in case someone else is also interested and if this could someday be merged here.

**Comment by nicolasbock** [comment]
There is #120 that proposed to add the ability to use podman in addition to docker. I think this would be an awesome feature addition.

**Comment by epsilon-0** [comment]
Closing this down to continue discussion there but will keep the fork and continue the work there as well :smile_cat:

**Comment by nicolasbock** [comment]
:+1:
