### ISSUE TITLE
What about removing base_packages?

### ISSUE THREAD

**Issue by stkw0** [nicolasbock/ebuildtester#130]
Personally I found it a waste of time to merge them as I almost never use it and the last time that Gentoo updated the default PYTHON_TARGETS the container failed to execute because there were conflicts when merging those base_packages.

**Comment by nicolasbock** [comment]
Yes, we could make that optional for example but disabled by default. Would that help?

**Comment by stkw0** [comment]
Yeah, that would be nice.
