### ISSUE TITLE
0.1.23 release?

### ISSUE THREAD

**Issue by xp-vit** [nicolasbock/ebuildtester#147]
Would you like to release 0.1.23? It contains nice fixes and improvements. Shall we add it to Gentoo tree.

BTW, Thanks for the great tool.

**Comment by nicolasbock** [comment]
Hi @xp-vit . Yes, let me do that. Thanks for the reminder!

**Comment by nicolasbock** [comment]
I release `v0.1.27` to and added it to portage.

**Comment by xp-vit** [comment]
New version works like a charm!! Thanks :-)
