### ISSUE TITLE
Support different arch profiles

### ISSUE THREAD

**Issue by stkw0** [nicolasbock/ebuildtester#152]
Now we are capable of specifying non-amd64 docker images, but if in accordance to it we try to use a non-amd64 profile we get an error like: ebuildtester: error: argument --profile: invalid choice: 'default/linux/arm/17.0' (choose from 'default/linux/amd64/17.1', 'default/linux/amd64/17.1/systemd')

It will be cool to try to improve the support for non-amd64 containers

**Comment by nicolasbock** [comment]
I wonder if we should just disable the check for what the user wants the profile to be. This will push a failure into the container though, but if we keep checking in the command line parser then we also need to make sure the list of allowed choices is always up to date. From a maintenance point of view, not restricting the choices is definitely better :smile:
