### ISSUE TITLE
--global-use not used

### ISSUE THREAD

**Issue by tastytea** [nicolasbock/ebuildtester#157]
Version: **0.1.29**

The useflags are not added to make.conf or to $USE. The command line was:

```
ebuildtester \
  --update \
  --pull \
  --threads 1 \
  --portage-dir "$(portageq get_repo_path / gentoo)" \
  --unstable \
  --overlay-dir ~/Projekte/guru \
  --with-X \
  --global-use "elogind" \
  --atom '=media-gfx/glimpse-0.2.0' '=dev-lang/rust-bin-1.51.0' 'sys-kernel/gentoo-sources-5.11.15'
```

I tried without `--width-X`, same result.

**Comment by nicolasbock** [comment]
Thanks for reporting @tastytea ! I can confirm that it's not working as intended. I am looking into what the issue is.

**Comment by nicolasbock** [comment]
@tastytea Could you try #158 and check whether it fixes this issue? Thanks!

**Comment by tastytea** [comment]
Yes, the flags are now recorded in make.conf. Thank you!
