### ISSUE TITLE
Error profile file not found

### ISSUE THREAD

**Issue by RafaelPalomar** [nicolasbock/ebuildtester#162]
I've tried `ebuildteter` through the following command:

```bash
buildtester --portage-dir /usr/portage\
                  --overlay-dir /home/rafael/src/gentoo\
                  --use R boost imaging python qt5 rendering views\
                  --unmask =sci-libs/vtk-9.0.1\
                  --with-X\
                  --atom =sci-libs/vtk-9.0.1
```
And get the following error:

```txt
 f9d51f eselect profile set default/linux/amd64/17.1
2022-01-10 15:25:50,838 - f9d51f (stderr): sed: can't read /var/db/repos/gentoo/profiles/profiles.desc: No such file or directory
2022-01-10 15:25:50,840 - f9d51f (stderr): !!! Error: default/linux/amd64/17.1 is not a valid profile for amd64
2022-01-10 15:25:50,840 - f9d51f (stderr): exiting
```
Any idea what could be wrong in here?

**Comment by RafaelPalomar** [comment]
It seems I was pointing my directories wrong.

**Comment by nicolasbock** [comment]
Hi @RafaelPalomar ! I am glad things are working for you. Please let me know if you run into any other issues.

**Comment by RafaelPalomar** [comment]
Thank you, @nicolasbock for your reply and for `ebuildtester`. It is really a fantastic tool. Have you thought about bringing `ccache` capabilities in?

**Comment by nicolasbock** [comment]
Hmm, no, but that sounds like a great idea. Let me create an issue for that.

**Comment by nicolasbock** [comment]
I created nicolasbock/ebuildtester#163 @RafaelPalomar
