### ISSUE TITLE
Move tester.log to a predefined directory

### ISSUE THREAD

**Issue by stkw0** [nicolasbock/ebuildtester#177]
Instead of creating tester.log on the working directory that ebuildtester is executed it may be good to store logs in some other place (in XDG standard directory for logs probably). The problem I have with the current behaviour is that sometimes I run ebuidltester in my fork of gentoo and if I forgot to check it sometimes i add & push tester.log too. Another inconvenience is that sometimes I execute tester.log in some folder where I was in a different directory and I forgot to remove it and I end up having tester.log files in different places.

**Comment by nicolasbock** [comment]
Thanks for the report @stkw0 ! I agree with you, I keep running into the same issues.

**Comment by nicolasbock** [comment]
Closed with nicolasbock/ebuildtester#179
