### ISSUE TITLE
Ebuildtester does not get installed through snap

### ISSUE THREAD

**Issue by RafaelPalomar** [nicolasbock/ebuildtester#195]
Trying to install ebuildtester through snap in Ubuntu 22.04 produces the following error:

```console
error: cannot perform the following tasks:
- Run configure hook of "ebuildtester" snap if present (run hook "configure": 
-----
Please run

snap connect ebuildtester:docker-executables docker:docker-executables

in order to use the ebuildtester command.
-----)
```
Issuing `snap connect ebuildtester:docker-executables docker:docker-executables` produces:
```
error: snap "ebuildtester" is not installed
```

**Comment by nicolasbock** [comment]
Duplicate of nicolasbock/ebuildtester#193

**Comment by nicolasbock** [comment]
Let me know if it works now.

**Comment by RafaelPalomar** [comment]
> Let me know if it works now.

That worked fine! Thank you very  much!
