### ISSUE TITLE
failure creating docker container

### ISSUE THREAD

**Issue by DaniD3v** [nicolasbock/ebuildtester#213]
ebuildtester --portage-dir /var/db/repos/danidev --atom "gui-apps/packettracer"
```
2023-11-13 15:24:04,065 - logging at /tmp/ebuildtester-gui-apps-packettracer.log
2023-11-13 15:24:04,065 - *** please note that all necessary licenses will be accepted ***
2023-11-13 15:24:04,065 - creating container
2023-11-13 15:24:04,065 - creating docker container with: docker create --tty --cap-add CAP_SYS_ADMIN --cap-add CAP_MKNOD --cap-add CAP_NET_ADMIN --security-opt apparmor:unconfined --device /dev/fuse --workdir /root --volume /var/db/repos/danidev:/var/db/repos/gentoo --volume /var/db/repos/danidev/distfiles:/var/cache/distfiles --volume /var/db/repos/danidev/packages:/var/cache/binpkgs gentoo/stage3
docker: unknown server OS: .
See 'docker create --help'.
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/ebuildtester", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/ebuildtester/main.py", line 23, in main
    container = Docker(
                ^^^^^^^
  File "/usr/lib/python3.11/site-packages/ebuildtester/docker.py", line 26, in __init__
    self._create_container(docker_image, local_portage,
  File "/usr/lib/python3.11/site-packages/ebuildtester/docker.py", line 184, in _create_container
    raise Exception("failure creating docker container")
Exception: failure creating docker container
```

equery l docker
```
 * Searching for docker ...
[IP-] [  ] app-containers/docker-24.0.5:0
```

equery l docker-clli
```
 * Searching for docker-cli ...
[IP-] [  ] app-containers/docker-cli-24.0.5:0
```

**Comment by stkw0** [comment]
Can you show the output of `cat /proc/version `?

**Comment by DaniD3v** [comment]
cat /proc/version
Linux version 6.1.60-gentoo-dist (portage@localhost) (x86_64-pc-linux-gnu-gcc (Gentoo 13.2.1_p20230826 p7) 13.2.1 20230826, GNU ld (Gentoo 2.40 p5) 2.40.0) #1 SMP PREEMPT_DYNAMIC Sat Nov 11 11:53:20 CET 2023

I updated in the meantime but I reproduced the error.

**Comment by stkw0** [comment]
Can you run `docker run hello-world`? Please ensure that you have enabled all the kernel config values that docker requires. When emerging app-containers/docker it checks if they are present and if not it shows a message about which options are lacking.  
Do you have any unusual set-up that could be related?

**Comment by DaniD3v** [comment]
`sudo docker run hello-world                                                                      ─╯
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
719385e32844: Pull complete
Digest: sha256:c79d06dfdfd3d3eb04cafd0dc2bacab0992ebc243e083cabe208bac4dd7759e0
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started`
 
 hello-world works (and Microsoft SQL and papermc also work)

**Comment by stkw0** [comment]
Yeah, everything seems right. I thought that maybe it was running from a virtual machine or that one part (cli or daemon) was from an older version, but it seems right. I understand that you also ran ebuildtester with sudo as you did with `sudo docker run hello-world`, right?  Have you checked that the required kernel settings are enabled?

**Comment by DaniD3v** [comment]
>I understand that you also ran ebuildtester with sudo as you did with `sudo docker run hello-world`, right? 

oh bruh I'm really sorry that should've been obvious. This should have its own error message tho. Can I make a PR?

**Comment by stkw0** [comment]
I think it's more a docker-cli issue. But it's a good idea to add a troubleshooting section in the README.md. 
fyi you don't really need to use sudo, if you want you can add your user to "docker" group. That will allow you to use docker and ebuildtester as your user.
