### ISSUE TITLE
fix: update default profile to 23.0

### ISSUE THREAD

**Issue by DerpDays** [nicolasbock/ebuildtester#220]
Currently the latest gentoo stage3 docker image now uses `merged-usr` by default, this means that the current default profile (which is meant to be `split-usr`) does not always work correctly for some ebuilds which have logic specifically for `split-usr` since they expect a split usr/bin and bin.

I believe we should update the default profile to `23.0` since `17.1` will stop being supported eventually and to resolve the aforementioned issue.

**Comment by stkw0** [comment]
Merged at https://github.com/nicolasbock/ebuildtester/commit/419bc865c52ea6d943be08d9bc15cd10c4cd0e34
