### ISSUE TITLE
Enable "live ebuilds"

### ISSUE THREAD

**Issue by nicolasbock** [nicolasbock/ebuildtester#42]
Live ebuilds need to be enabled by adding
~~~
ATOM **
~~~
to `/etc/portage/package.accept_keywords`.

**Comment by stkw0** [comment]
Is this the same that the already implemented "--live-ebuild" option?

**Comment by nicolasbock** [comment]
Yes, good point. I guess I am getting forgetful :wink: Let's close this issue. Thanks for pointing that out!
