### ISSUE TITLE
--global-use option not used

### ISSUE THREAD

**Issue by waebbl** [nicolasbock/ebuildtester#92]
I was just wondering why boost-build in a container didn't have the python use flag enabled, although I added --global-use python to the command.
Grepping the files, I noticed, that it's defined in parse.py, but it's currently not used anywhere.

**Comment by nicolasbock** [comment]
Hmm, yes you are right :disappointed: Thanks for reporting! i'll fix it in the next release. Or if you feel adventurous please feel free to open a pull request :smile:

Thanks!
